### ISSUE TITLE
invalid redefinition of constant from parametric type

### ISSUE THREAD

**Issue by marius311** [cstjean/ClobberingReload.jl#1]
Basically just this issue, which ClobberringReload seems to suffer from also: https://github.com/malmaud/Autoreload.jl/issues/23

If the file getting reloaded contains a parametric type, you get an "invalid redefinition of constant" error. I've tested this on Julia 0.5 and current master (09422440adc7d593dd2ce462dadd1b7c148db578).

**Comment by cstjean** [comment]
Yes, this is really unfortunate, but the good news is that the issue has been solved on julia-master by [#17618](https://github.com/JuliaLang/julia/pull/17618) (though I haven't tested it). I'm hopeful that this can be backported to 0.5.1, and will be suggesting it when the time comes.

**Comment by marius311** [comment]
Ah, good to know, thanks. Is there any way to prevent ClobberingReload from trying to reevaluate those types, as a workaround until that fix hits a stable Julia version?

**Comment by cstjean** [comment]
We could follow @malmaud's suggestion to strip out the type definition from the AST before passing it to eval. There are some issues with that:
- Changes to the constructors will be ignored
- It won't work if the type definition is inside a macro expansion

But that's fine, I suppose. We could have a global boolean to turn it on. PRs welcome.

**Comment by cstjean** [comment]
And we'd have to expand the `include`s to cover their parametric types...

**Comment by rdeits** [comment]
I'm actually still getting this error on the latest v0.6-dev, unfortunately.

**Comment by cstjean** [comment]
Can anyone please check if executing

```julia
immutable X{T}
   a::T
end
```

twice at the REPL on 0.6 triggers an error?

**Comment by rdeits** [comment]
Yeah, it does:

```juila
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.0-dev.2778 (2017-02-12 11:20 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 71f6bc9 (0 days old master)
|__/                   |  x86_64-apple-darwin13.4.0

julia> immutable X{T}
          a::T
       end

julia> immutable X{T}
          a::T
       end
ERROR: invalid redefinition of constant X
```

**Comment by cstjean** [comment]
Sorry that I didn't handle it for 0.5, but this is fixed on 0.6 thanks to changes in Base 🎉

**Comment by skariel** [comment]
this is not solved for self referential types. In Julia 0.6:

```Julia
struct ABC
    z::ABC
    function ABC()
        n = new()
        n.z = n
        n
    end
end

struct ABC
    z::ABC
    function ABC()
        n = new()
        n.z = n
        n
    end
end
```
results in:
```
invalid redefinition of constant ABC

Stacktrace:
 [1] include_string(::String, ::String) at ./loading.jl:515
```

I'll open a new issue

**Comment by skariel** [comment]
see new issue here: #24270

**Comment by cstjean** [comment]
Have you tried [Revise.jl](https://github.com/timholy/Revise.jl)? I'm probably going to deprecate ClobberingReload.jl, because Revise.jl is pretty much uniformly nicer. It doesn't suffer from the struct-redefinition problem.

Thoughts?

**Comment by rdeits** [comment]
For my part, I've stopped using ClobberingReload in favor of Revise. It is pretty magical 😄
